SET(CTEST_SOURCE_DIRECTORY "$ENV{HOME}/code/MOOS++/src")
SET(CTEST_BINARY_DIRECTORY "$ENV{HOME}/code/MOOS++/build_test")
SET(CTEST_CMAKE_GENERATOR "Unix Makefiles")

    CTEST_START("Experimental")
    CTEST_CONFIGURE(BUILD "${CTEST_BINARY_DIRECTORY}")
    CTEST_BUILD(BUILD "${CTEST_BINARY_DIRECTORY}")
    CTEST_TEST(BUILD "${CTEST_BINARY_DIRECTORY}")
    CTEST_SUBMIT()
